
BACK_UP="\033[1K\033[0G"
NORMAL="\033[0m"
WARN="\033[33;1m"
BAD="\033[31;1m"
BOLD="\033[1m"
GOOD="\033[32;1m"

# Reset FB Colour Mode
RESET="]R"
# Erase to End of Line
CRE="[K"
# Clear and Reset Screen
CLEAR="c"

# Normal color
NORMAL="[0;39m"
# Failure or Error Message
RED="[1;31m"
# Success Message
GREEN="[1;32m"
# Descriptions
YELLOW="[1;33m"
# System Messages
BLUE="[1;34m"
# Found devices or drivers
MAGENTA="[1;35m"
# Questions
CYAN="[1;36m"
# Hint
WHITE="[1;37m"

# place to setup system before running
NEW_ROOT="/mnt/root"
